# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create working directory
WORKDIR /app

# Copy package files and install dependencies without running scripts
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile --ignore-scripts

# Copy TypeScript configuration and source code
COPY tsconfig.json ./
COPY src ./src
COPY scripts ./scripts

# Build the project
RUN pnpm run build

# Expose port if needed

# Run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
